### ISSUE TITLE
Windows 10 installation issue

### ISSUE THREAD

**Issue by venugovh** [Relu-bv/PyVoxSurf#1]
Hi @AndreasSmoldersRelu and @a3VonG  !

I am trying to install `pyvoxsurf` in windows 10 for python 3.7. Could you please tell me how to do that? 

This is the issue I am facing when I try to install:
```
python setup.py install --user
running install
running bdist_egg
running egg_info
writing pyvoxsurf.egg-info\PKG-INFO
writing dependency_links to pyvoxsurf.egg-info\dependency_links.txt
writing top-level names to pyvoxsurf.egg-info\top_level.txt
reading manifest file 'pyvoxsurf.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'pyvoxsurf.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.29.30136.0
-- The CXX compiler identification is MSVC 19.29.30136.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:4 (add_subdirectory):
  The source directory

    C:/Users/<Username>/Desktop/pyvox/PyVoxSurf/lib/LibSL-small

  does not contain a CMakeLists.txt file.


-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS CXX) (found version "")
CMake Error at CMakeLists.txt:20 (set_target_properties):
  set_target_properties Can not find target to add properties to: LibSL


-- Could NOT find Python (missing: Python_EXECUTABLE Python_NumPy_INCLUDE_DIRS Interpreter NumPy)
CMake Error at CMakeLists.txt:24 (add_subdirectory):
  The source directory

    C:/Users/<Username>/Desktop/pyvox/PyVoxSurf/lib/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:25 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "C:/Users/<Username>/Desktop/pyvox/PyVoxSurf/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    zip_safe=False,
  File "C:\Users\<Username>\Desktop\pyvox\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\<Username>\Desktop\pyvox\venv\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\<Username>\Desktop\pyvox\venv\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\<Username>\Desktop\pyvox\venv\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\<Username>\Desktop\pyvox\venv\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\<Username>\Desktop\pyvox\venv\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 38, in run
    self.build_extension(ext)
  File "setup.py", line 70, in build_extension
    ["cmake", ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env
  File "C:\Users\<Username>\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\<Username>\\Desktop\\pyvox\\PyVoxSurf', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\<Username>\\Desktop\\pyvox\\PyVoxSurf\\build\\lib.win-amd64-3.7', '-DPYTHON_EXECUTABLE=C:\\Users
\\<Username>\\Desktop\\pyvox\\venv\\Scripts\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\<Username>\\Desktop\\pyvox\\PyVoxSurf\\build\\lib.win-amd64-3.7', '-A', 'x64']' returned non-zero exit status 1.
```

Thanks!

**Comment by a3VonG** [comment]
Dear, please checkout the original repo: https://github.com/sylefeb/VoxSurf for instructions :)
